#include <database/TableRegistry.hpp>

#include <algorithm>

namespace fasc::server::database {
namespace {

using C = ColumnSchema;
using K = ColumnKind;

const std::vector<TableSchema> kTables = {
    {"association_employee",
     {C{"id", K::Integer, true, true}, C{"person_id", K::Integer, true},
      C{"association_id", K::Integer, true}, C{"role_id", K::Integer, true},
      C{"employment_status_id", K::Integer, true}, C{"hire_date", K::Text, true},
      C{"dismissal_date"}, C{"salary", K::Numeric}, C{"contract_number"}},
     {"id"}},
    {"association_farms",
     {C{"farm_id", K::Integer, true}, C{"association_id", K::Integer, true},
      C{"join_date", K::Text, true}, C{"status"}, C{"notes"}},
     {"farm_id", "association_id"}},
    {"association_member",
     {C{"id", K::Integer, true, true}, C{"association_id", K::Integer, true},
      C{"person_id", K::Integer, true}, C{"membership_number"}, C{"joined_date", K::Text, true},
      C{"status"}, C{"notes"}},
     {"id"}},
    {"association_role",
     {C{"id", K::Integer, true}, C{"code"}, C{"name"}, C{"description"}},
     {"id"}},
    {"contract",
     {C{"id", K::Integer, true, true}, C{"supplier_id", K::Integer},
      C{"farm_id", K::Integer}, C{"association_id", K::Integer, true}, C{"contract_number"},
      C{"sign_date", K::Text, true}, C{"start_date", K::Text, true}, C{"end_date"},
      C{"status"}, C{"description"}},
     {"id"}},
    {"employee_plot_assignment",
     {C{"id", K::Integer, true, true}, C{"farm_employee_id", K::Integer, true},
      C{"farm_plot_id", K::Integer, true}, C{"assignment_type"}, C{"assigned_at", K::Text, true},
      C{"unassigned_at"}, C{"notes"}},
     {"id"}},
    {"employment_status", {C{"id", K::Integer, true}, C{"name"}}, {"id"}},
    {"farm",
     {C{"id", K::Integer, true, true}, C{"name"}, C{"legal_name"}, C{"legal_address"},
      C{"actual_address"}, C{"inn"}, C{"ogrn"}, C{"status"}, C{"farm_type"}},
     {"id"}},
    {"farm_association",
     {C{"id", K::Integer, true, true}, C{"inn"}, C{"ogrn"}, C{"name"}, C{"legal_address"},
      C{"status"}},
     {"id"}},
    {"farm_employee",
     {C{"id", K::Integer, true, true}, C{"person_id", K::Integer, true},
      C{"farm_id", K::Integer, true}, C{"role_id", K::Integer, true},
      C{"employment_status_id", K::Integer, true}, C{"hire_date", K::Text, true},
      C{"dismissal_date"}, C{"salary", K::Numeric}, C{"employment_contract_number"},
      C{"is_primary_workplace", K::Integer}},
     {"id"}},
    {"farm_owner",
     {C{"id", K::Integer, true, true}, C{"person_id", K::Integer, true}, C{"status"},
      C{"rating", K::Numeric}},
     {"id"}},
    {"farm_ownership",
     {C{"id", K::Integer, true, true}, C{"farm_id", K::Integer, true},
      C{"farm_owner_id", K::Integer, true}, C{"ownership_percentage", K::Numeric},
      C{"started_at", K::Text, true}, C{"ended_at"}},
     {"id"}},
    {"farm_plot",
     {C{"id", K::Integer, true, true}, C{"farm_plot_type_id", K::Integer}, C{"name"},
      C{"area", K::Numeric}, C{"location"}, C{"cadastral_number"}, C{"status"}},
     {"id"}},
    {"farm_plot_assignment",
     {C{"farm_id", K::Integer, true}, C{"farm_plot_id", K::Integer, true}, C{"status"},
      C{"notes"}},
     {"farm_id", "farm_plot_id"}},
    {"farm_plot_consumption_product",
     {C{"product_id", K::Integer, true}, C{"farm_plot_id", K::Integer, true},
      C{"quantity", K::Integer, true}, C{"consumption_now", K::Integer, true}},
     {"product_id", "farm_plot_id"}},
    {"farm_plot_production_product",
     {C{"product_id", K::Integer, true}, C{"farm_plot_id", K::Integer, true},
      C{"quantity", K::Integer, true}, C{"production_now", K::Integer, true}},
     {"product_id", "farm_plot_id"}},
    {"farm_plot_type",
     {C{"id", K::Integer, true}, C{"name"}, C{"description"},
      C{"farm_plot_level", K::Integer, true}, C{"parent_id", K::Integer}},
     {"id"}},
    {"farm_role", {C{"id", K::Integer, true}, C{"name"}, C{"description"}}, {"id"}},
    {"identity_document_type",
     {C{"id", K::Integer, true}, C{"code"}, C{"name"}, C{"description"}},
     {"id"}},
    {"person",
     {C{"id", K::Integer, true, true}, C{"first_name"}, C{"last_name"}, C{"middle_name"},
      C{"birth_date"}, C{"phone"}, C{"email"}, C{"address"}},
     {"id"}},
    {"person_document",
     {C{"id", K::Integer, true, true}, C{"person_id", K::Integer, true},
      C{"document_type_id", K::Integer, true}, C{"document_number"}, C{"issued_by"},
      C{"issued_date"}, C{"expiration_date"}, C{"is_primary", K::Integer}},
     {"id"}},
    {"product",
     {C{"id", K::Integer, true, true}, C{"type_id", K::Integer, true}, C{"name"},
      C{"unit_id", K::Integer}},
     {"id"}},
    {"product_type",
     {C{"id", K::Integer, true}, C{"parent_id", K::Integer}, C{"sku"},
      C{"product_level", K::Integer, true}, C{"name"}, C{"description"}},
     {"id"}},
    {"purchase_order",
     {C{"id", K::Integer, true, true}, C{"association_id", K::Integer, true},
      C{"supplier_id", K::Integer, true}, C{"delivery_address"}, C{"order_date", K::Text, true},
      C{"expected_delivery_date"}, C{"status"}, C{"total_amount", K::Numeric}, C{"received_at"},
      C{"created_by", K::Integer}},
     {"id"}},
    {"purchase_order_item",
     {C{"id", K::Integer, true, true}, C{"purchase_order_id", K::Integer, true},
      C{"product_id", K::Integer, true}, C{"quantity", K::Numeric}, C{"unit_price", K::Numeric},
      C{"vat_rate", K::Numeric}, C{"currency"}},
     {"id"}},
    {"purchase_requisition",
     {C{"id", K::Integer, true, true}, C{"farm_id", K::Integer, true},
      C{"product_id", K::Integer, true}, C{"quantity", K::Integer, true},
      C{"max_price_per_unit", K::Numeric}, C{"offer_date"}, C{"required_date"},
      C{"priority", K::Integer}, C{"valid_until"}, C{"status"}, C{"notes"}},
     {"id"}},
    {"sales_requisition",
     {C{"id", K::Integer, true, true}, C{"farm_id", K::Integer},
      C{"product_id", K::Integer, true}, C{"quantity", K::Integer, true},
      C{"price_per_unit", K::Numeric}, C{"offer_date", K::Text, true}, C{"valid_until"},
      C{"status"}, C{"notes"}},
     {"id"}},
    {"supplier",
     {C{"id", K::Integer, true, true}, C{"name"}, C{"legal_address"}, C{"status"}},
     {"id"}},
    {"supplier_product_price",
     {C{"id", K::Integer, true, true}, C{"supplier_id", K::Integer, true},
      C{"product_id", K::Integer, true}, C{"purchase_price", K::Numeric},
      C{"valid_from", K::Text, true}, C{"valid_until"}},
     {"id"}},
    {"unit", {C{"id", K::Integer, true}, C{"code"}, C{"name"}}, {"id"}},
};

} // namespace

const TableSchema* findTable(std::string_view name) {
  const auto it = std::find_if(kTables.begin(), kTables.end(),
                               [&](const TableSchema& table) { return table.name == name; });
  return it == kTables.end() ? nullptr : &*it;
}

const std::vector<TableSchema>& allTables() {
  return kTables;
}

} // namespace fasc::server::database
